# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf2b199496fa61a2f934f40b1ed1d71f3f5e9aeea8b6da2465cd1932cfd3c313f12259087b20190c883aa3fe96b2b410f7153bbd4b33316172a32d7658d4587

test:
  secret_key_base: 71c82d1c45ec4e71e6ffcf5975d39389e6fb19c2aba73a824db581f00e2a7df3df6b64bcaf04fba31aa2dea2109ac5fffe24d74dad83a4407fdece5b4e348b44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
